### ISSUE TITLE
Export files with WordPress locale (wp_locale)

### ISSUE THREAD

**Issue by pedro-mendonca** [mayukojpn/gp-live-export#6]
Hi @mayukojpn ,

Congratulations for this simple and very nice plugin!

After testing your plugin [Force Update Translations](https://github.com/mayukojpn/force-update-translations) and checked that it exports the .po and .mo files with the correct locale, I suggest this plugin does the same.

Example:
For Portuguese (pt_PT) the files are exported as `plugin-slug_pt.po` but it should use the correct wp_locale `plugin-slug_pt_PT.po` as it's currently working on Force Update Translations by using the library [locales.php](https://github.com/mayukojpn/force-update-translations/blob/master/lib/glotpress/locales.php).

Regards

**Comment by mayukojpn** [comment]
Thank you for heading up @pedro-mendonca ! I might be busy in this month for WordCamp Manila and Tokyo, but I'll check it later :)

**Comment by pedro-mendonca** [comment]
@mayukojpn I've got a solution but this repo isn't updated comparing to the v0.3 of wp.org directory.
Can you please update it so I can patch according the latest code?

**Comment by mayukojpn** [comment]
@pedro-mendonca Thanks! And I'm sorry I don't really taking care of it 😭I pushed all commit!

**Comment by pedro-mendonca** [comment]
@mayukojpn I'm closing this issue as it was solved in https://github.com/mayukojpn/gp-live-export/pull/7
